### ISSUE TITLE
Group Membership Lookup Recursive

### ISSUE THREAD

**Issue by reach4bawer** [zorn96/ms_active_directory#15]
I tried to look up membership of the administrator group and I am getting the following error -

```
from ms_active_directory import ADDomain
from ldap3 import SASL, KERBEROS

domain = ADDomain('DOMAIN.Test.COM')

ad_group = 'Administrators'
users = session.find_members_of_group_recursive(ad_group, desired_attrs)
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/user/.local/lib/python3.7/site-packages/ms_active_directory/core/ad_session.py", line 1739, in find_members_of_group_recursive
    maximum_nesting_depth=maximum_nesting_depth)
  File "/home/user/.local/lib/python3.7/site-packages/ms_active_directory/core/ad_session.py", line 1786, in find_members_of_groups_recursive
    controls=controls, skip_validation=skip_validation)
  File "/home/user/.local/lib/python3.7/site-packages/ms_active_directory/core/ad_session.py", line 1678, in find_members_of_groups
    ad_obj = self.find_object_by_distinguished_name(member_dn, attributes_to_lookup, controls=controls)
  File "/home/user/.local/lib/python3.7/site-packages/ms_active_directory/core/ad_session.py", line 1050, in find_object_by_distinguished_name
    BASE, attributes_to_lookup, 1, ADObject, controls=controls)
  File "/home/user/.local/lib/python3.7/site-packages/ms_active_directory/core/ad_session.py", line 744, in _find_ad_objects_and_attrs
    'response: {}'.format(result))
ms_active_directory.exceptions.DomainSearchException: An error was encountered searching the domain; this may be due to a permission issue or an domain resource availability issue. Raw response: {'result': 32, 'description': 'noSuchObject', 'dn': 'DC=DOMAIN,DC=Test,DC=com', 'message': "0000208D: NameErr: DSID-03100241, problem 2001 (NO_OBJECT), data 0, best match of:\n\t'DC=DOMAIN,DC=Test,DC=com'\n\x00", 'referrals': None, 'type': 'searchResDone'}
```
There was a SID value that Administrators group had from a different domain and it was deleted. So I think it might be a hanging SID which is breaking.

**Comment by zorn96** [comment]
ah yeah that'd do it. if there's a member in the group that no longer exists then this function is designed to error by default.

but I'd intended for the error message to be better. I just pushed a release to improve the error (it wasn't propagating correctly).
there's actually already a way to get around this issue. there's a `skip_validation` keyword argument that you can use. it's covered in the docstring
```
        :param skip_validation: If true, assume all members exist and do not raise an error if we fail to look one up.
                                Instead, a placeholder object will be used for members that could not be found.
                                Defaults to False.
```

and the code for the better error message that I'd intended
```
        for member_dn in all_member_dns_set:
            ad_obj = self.find_object_by_distinguished_name(member_dn, attributes_to_lookup, controls=controls)
            if ad_obj is None:
                if skip_validation:
                    # use a placeholder object with just the dn
                    ad_obj = ADObject(member_dn, {}, self.domain)
                else:
                    raise DomainSearchException('An object with distinguished name {} was listed as a member of a '
                                                'group but information about it could not be found when searching the '
                                                'domain. This may indicate that the object was deleted in parallel '
                                                'with this search being performed, or an issue with the permissions '
                                                'of this session. If you believe it was a race with the domain '
                                                'changing, please retry this operation. Otherwise, please examine the '
                                                'permissions of the session.'.format(member_dn))
```

if you update to 1.9.1 and change to use
`users = session.find_members_of_group_recursive(ad_group, desired_attrs, skip_validation=True)`
then it should work :)

**Comment by reach4bawer** [comment]
Thanks for the example. Would the function be able to resolve foreign objects while doing the lookup?

**Comment by zorn96** [comment]
It can find them but they’re just returned as generic ADObject objects right now.
In the Future I plan to expand on multi domain functionality and provide functions for using foreign security principals to find group memberships across domains. Right now you’d need to map things across domains yourself using the find by sid functions
