### ISSUE TITLE
AD password reset don't work

### ISSUE THREAD

**Issue by ericogamo** [zorn96/ms_active_directory#49]
I want to reset a password

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/websockets/legacy/server.py", line 232, in handler
    await self.ws_handler(self)
  File "/home/container/server.py", line 143, in echo
    await websocket.send(WAD.main(message_json))
  File "/home/container/server.py", line 48, in main
    if auth_session.reset_password_for_account(WAD, "CN=test,OU=Service,DC=Alpha-Games,DC=de", "123456789@test"):
  File "/home/container/.local/lib/python3.10/site-packages/ms_active_directory/core/ad_session.py", line 3119, in reset_password_for_account
    return self.change_password_for_account(account, new_password, None, skip_validation=skip_validation)
  File "/home/container/.local/lib/python3.10/site-packages/ms_active_directory/core/ad_session.py", line 3098, in change_password_for_account
    account = self._validate_user_and_get_user_obj(account, can_be_computer=True, skip_validation=skip_validation)
  File "/home/container/.local/lib/python3.10/site-packages/ms_active_directory/core/ad_session.py", line 3903, in _validate_user_and_get_user_obj
    raise InvalidLdapParameterException('The user specified must be an ADUser object or a string user name.')
ms_active_directory.exceptions.InvalidLdapParameterException: The user specified must be an ADUser object or a string user name.

**Comment by zorn96** [comment]
hi @ericogamo ! it looks like you're calling the function with some incorrect parameters.
the function signature is 
```
    def reset_password_for_account(self, account: Union[str, ADUser, ADComputer], new_password: str,
                                   skip_validation: bool = False) -> bool:
```
so you would call it in the style `auth_session.reset_password_for_account(account_name, new_password)`
but it looks like you have 3 paramters `auth_session.reset_password_for_account(WAD, "CN=test,OU=Service,DC=Alpha-Games,DC=de", "123456789@test")`. I'm not sure what `WAD` is but it seems like you don't want that to be passed in

let me know if you run into any other issues
